# Generated by Django 3.0.4 on 2020-03-23 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('persian_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('register_deadline', models.DateTimeField()),
                ('register_deadline_str', models.CharField(blank=True, default='۱۵ فروردین ۱۳۹۹', max_length=30, null=True)),
                ('title', models.CharField(blank=True, default='عنوان', max_length=30, null=True)),
                ('full_description', models.TextField(blank=True, default='', null=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cover', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('banner', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('register_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instructor', models.CharField(blank=True, default='مهندس جمشیدی', max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_str', models.CharField(blank=True, default='۱۵ فروردین ۱۳۹۹', max_length=30, null=True)),
                ('title', models.CharField(blank=True, default='عنوان', max_length=30, null=True)),
                ('full_description', models.TextField(blank=True, default='', null=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('div_element', models.TextField(blank=True, default='', null=True)),
                ('cover', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('author', models.CharField(blank=True, default='مهندس جمشیدی', max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Category')),
            ],
        ),
    ]
