# Generated by Django 3.0.4 on 2020-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='postCovers/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='programBanner/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='programCover/'),
        ),
    ]
