# Generated by Django 3.0.4 on 2020-03-24 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='register_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
